### ISSUE TITLE
Is this working or how do i use it

### ISSUE THREAD

**Issue by OsirisKing** [dealloc/icarus_editor#3] opened 2023-02-08 21:47 UTC
hello, im trying to use the save editor but when i try to open it i get an error that says "icarus failed to load instance of 'IcaursExeption' what am i doing wrong?

**Comment by dealloc** [comment] 2023-02-08 21:54
Are your save files located under your Appdata\Local\Icarus\Saved?
If possible, can you provide a screenshot of the specific error being shown on the screen?

**Comment by OsirisKing** [comment] 2023-02-08 21:56
<img width="950" alt="Screenshot 2023-02-08 155620" src="https://user-images.githubusercontent.com/49198682/217660256-fe309b78-c918-4da9-8c38-39f4f8dfe157.png">

**Comment by OsirisKing** [comment] 2023-02-08 21:57
AppData\Local\Icarus\Saved\PlayerData\

**Comment by OsirisKing** [comment] 2023-02-08 21:59
well its technically in \AppData\Local\Icarus\Saved\PlayerData\steamid

**Comment by dealloc** [comment] 2023-02-08 22:12
I've just pushed v0.0.3 (see [build](https://github.com/dealloc/icarus_editor/actions/runs/4128853678)).
Could you give that a try, it should provide a clearer error message about what's going on

**Comment by OsirisKing** [comment] 2023-02-08 22:13
yep i can do that

**Comment by OsirisKing** [comment] 2023-02-08 22:14
ahh it looks like its still working on it, ill give it a try after its finished

**Comment by OsirisKing** [comment] 2023-02-08 22:18
they have errors, were they still released?

**Comment by dealloc** [comment] 2023-02-08 22:34
looks like Flutter broke something which caused the build to fail, I'll get on fixing that first

**Comment by OsirisKing** [comment] 2023-02-08 22:39
no worries man, just let me know and i can give it a try to see what happens for you

**Comment by dealloc** [comment] 2023-02-08 22:42
seems like FluentUI fixed this in https://github.com/bdlukaa/fluent_ui/issues/568
let's see if 47ff90ac72cb6b02320c75e91f8f6ec637ee1894 fixes that

**Comment by OsirisKing** [comment] 2023-02-08 22:44
okay sweet

**Comment by dealloc** [comment] 2023-02-08 22:49
@OsirisKing v0.0.3 should be released now, note that it won't fix the issue you're having but it should provide a bit more information what exactly is going wrong now

**Comment by OsirisKing** [comment] 2023-02-08 22:50
awesome, as long as we can get an idea of whats happening

**Comment by OsirisKing** [comment] 2023-02-08 22:53
same error unfortunately

**Comment by OsirisKing** [comment] 2023-02-08 22:54
should i be putting this in a certain place or is on the desktop fine?

**Comment by dealloc** [comment] 2023-02-10 15:56
This should work from any location, I'm not clear why it's not working the way it should.
Is that screenshot from version 0.0.3?

**Comment by OsirisKing** [comment] 2023-02-10 18:35
Yes this is from 0.0.3, was the same error from 0.0.2 unfortunately

**Comment by dealloc** [comment] 2023-02-17 08:55
@OsirisKing just an update to let you know I haven't forgotten about this.
It's been quite hectic at work here, I'll try to get to this ASAP

**Comment by OsirisKing** [comment] 2023-02-17 20:10
No worries, I definitely understand. I appreciate the response though

**Comment by MichaelJmad** [comment] 2023-03-03 20:27
No rush but wanted to let you know that its doing the same for me,
save location "C:\Users\MichaelJMAD\AppData\Local\Icarus\Saved\PlayerData\SteamId"
and its v0.0.3

**Comment by dealloc** [comment] 2023-03-18 13:24
@OsirisKing, @MichaelJmad it's taken me a while to get back to both of you, my apologies.
I still can't reproduce the error you're both getting, however in v0.0.4 (just released) the new version should provide more information, and more importantly it should now also create a txt file called `log.txt` in the same directory as the executable.

Could both of you test if you're still receiving the error, and provide me with the logfile as well as a ZIP file containing your playerdata (the folder under Icarus\Saved\PlayerData zipped entirely).

Thanks in advance for your patience.

**Comment by NEOyoyo174** [comment] 2023-03-18 17:32
Hello, I provide the error log file
[log.txt](https://github.com/dealloc/icarus_editor/files/11009187/log.txt)

**Comment by NEOyoyo174** [comment] 2023-03-18 17:36
And PlayerData
[PlayerData.zip](https://github.com/dealloc/icarus_editor/files/11009199/PlayerData.zip)

**Comment by dealloc** [comment] 2023-03-18 18:43
@NEOyoyo174 I've identified the issue!
Apparently your profile.json file doesn't contain the Exotics field by default, which I assumed would always be present.

I'm pushing out a fix as I write this, so look forward to v0.0.5 which will (🤞🤞🤞) work for you as well.

**Closed** 2023-03-18 18:43 UTC

**Comment by NEOyoyo174** [comment] 2023-03-19 04:01
Hooray! The program has started! But it is impossible to change the exotic. Currency change works.

**Comment by NEOyoyo174** [comment] 2023-03-19 06:44
To edit exotics, you need to complete any mission in order to get a certain amount of the resource. Thanks for the work program, you're cool!

**Comment by dealloc** [comment] 2023-03-19 09:23
From what I could tell of your save files you haven't completed the required mission yet to unlock exotics, which this program won't change.
Once I figure out how Icarus handles "completing" missions, I could see about adding that, but for now you'll have to grind them I'm afraid :)
